---
- name: Configure Razer Blade laptop
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - packages.yaml

  pre_tasks:
    #- name: Parse OS-release
      #set_fact:
        #ubuntu_codename: "{{ lookup('ini', 'UBUNTU_CODENAME type=properties file=/etc/os-release') }}"
    - name: Set ansible_python_interpreter to pipx
      set_fact:
        ansible_python_interpreter: "{{ lookup('env', 'HOME') }}/.asdf/shims/pip"

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_update_result
      ignore_errors: true

    - name: Check for apt update timeout
      ansible.builtin.fail:
        msg: "Apt update failed. Timeout reached."
      when: apt_update_result.failed and 'Timeout' in apt_update_result.msg


  roles:
    - role: install_apt
      vars:
        packages_by_sections: "{{ apt }}"
      tags: ['apt']
    - role: install_ppa
      vars:
        ppas: "{{ ppa }}"
      tags: ['ppa']
    - role: install_pip
      vars:
        pips: "{{ pip }}"
      tags: ['pip']
    - role: ansible-role-docker
      tags: ['docker']
    - role: geerlingguy.swap
      vars:
        swap_file_size_mb: '10240'
      tags: ['swap']
    - role: dotfiles
      tags: ['dotfiles']

  #tasks:
    #- name: Print all available variables
      #debug:
        #msg: "{{ apt }}"
        #var: vars | dict2items | map(attribute='key') | list
        #var: hostvars[inventory_hostname]
