---
- name: Configure dotfiles
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - dotfile_packages.yaml

  vars:
    ppa:
      neovim:
        section: editors
        origin: Neovim Unstable:22.04/jammy [amd64]
        description: Fork of Vim aiming to improve user experience, plugins, and GUIs.
        source: ppa:neovim-ppa/unstable

  pre_tasks:
    - name: Parse OS-release
      set_fact:
        ubuntu_codename: "{{ lookup('ini', 'UBUNTU_CODENAME type=properties file=/etc/os-release') }}"

  roles:
    - role: install_apt
      vars:
        packages_by_sections: "{{ apt }}"
    - role: install_ppa
      vars:
        ppas: "{{ ppa }}"
      tags: ['ppa']
    - role: install_font
      vars:
        font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip"
        font_name: "Hack"
    - role: dotfiles
      tags: ['dotfiles']
