---
- name: Configure Razer Blade laptop
  hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - packages.yaml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_update_result
      ignore_errors: yes

    - name: Check for apt update timeout
      ansible.builtin.fail:
        msg: "Apt update failed. Timeout reached."
      when: apt_update_result.failed and 'Timeout' in apt_update_result.msg


  roles:
    - role: install_apt
      vars:
        packages_by_sections: "{{ apt }}"
      tags: ['apt']
    - role: install_ppa
      vars:
        ppas: "{{ ppa }}"
      tags: ['ppa']
    - role: install_pip
      vars:
        pips: "{{ pip }}"
      tags: ['pip']
    - role: install_docker
      vars:
        docker_images:
          - portainer/portainer-ce
          - ubuntu
      tags: ['docker']
    - role: geerlingguy.swap
      vars:
        swap_file_size_mb: '10240'
      tags: ['swap']
    - role: dotfiles
      tags: ['dotfiles']

  #tasks:
    #- name: Print all available variables
      #debug:
        #msg: "{{ apt }}"
        #var: vars | dict2items | map(attribute='key') | list
        #var: hostvars[inventory_hostname]
