---
- name: Install prerequisites
  include_tasks: install_prerequisites.yaml

- name: Clone github repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
  become: false

- name: Install symlinks
  command: /home/zacsek/dotfiles/install.sh -av

