---
- name: Iterate over section
  apt:
    name: "{{ package_name }}"
    state: present
  ignore_errors: true
  loop: "{{ section_content | dict2items }}"
  loop_control:
    loop_var: package
  vars:
    package_name: "{{ package.key }}"
    package_info: "{{ package.value }}"
